CATALOGUE_HOST: catalogue.vinnimakeovers.online
USER_HOST: user.vinnimakeovers.online
CART_HOST: cart.vinnimakeovers.online
SHIPPING_HOST: shipping.vinnimakeovers.online
PAYMENT_HOST: payment.vinnimakeover.online